---
title: English Literature
subtitle: The Bare Minimum for BCS
author: Susmit Islam
institute: Sir Salimullah Medical College
documentclass: beamer
output:
 beamer_presentation:
  keep_tex: yes
theme: metropolis
classoption: progressbar=frametitle
fontsize: 12pt
urlcolor: blue
linkcolor: blue
header-includes:
  - \setbeamersize{text margin left=10mm,text margin right=10mm}
  - \makeatletter
  - \setbeamertemplate{frametitle continuation}{- \usebeamerfont{frametitle}\insertcontinuationcount/\the\numexpr\beamer@endpageofframe+1-\beamer@startpageofframe}
  - \makeatother
  - \usepackage{bangla}
  - \usepackage{hyperref}
  - \usepackage{enumitem}
  - \setlistdepth{20}
  - \renewlist{itemize}{itemize}{20}
  - \renewlist{enumerate}{enumerate}{20}
  - \setlist[itemize]{label=$\boldsymbol\hookrightarrow$, leftmargin=5mm}
  - \setlist[itemize,1]{label=\tiny$\blacksquare$}
  - \setlist[itemize,2]{label=$\bullet$}
  - \setlist[itemize,3]{label=$\boldsymbol\circ$}
  - \setlist[itemize,4]{label=$\boldsymbol\hookrightarrow$}
  - \linespread{1.3}
  - \setlength{\fboxsep}{10pt}
  - \newcommand{\blockhead}[1]{\large\textbf{#1}\normalsize\vspace{-3mm}}
  - \newcommand{\btx}[1]{\footnotesize\banglatext{#1}\;\normalsize}
---
# Preface {-}
What follows are my own notes on English Literature for BCS. There probably
 are plenty of mistakes, and I apologise if anyone reading this has found any.
 These notes have been made, first and foremost, for personal use, so
 verify anything that seems off (or better, even anything that doesn't).
 Let me know of the errors.

 It's a work in progress, so make sure you're reading the latest version,
 which you can \href{https://github.com/susmit31/bcs-notes/raw/master/pdfs/lit.pdf}
 {fetch from here}.

 **Use at your own peril.**

\hfill Susmit Islam

\hfill \today

# Periods of English Literature
- **Mnemonic:** \btx{অমি রান্না নিয়ে রুমি ভাই এর মন পেল}
	- Old age / Anglo-Saxon period
	- Middle age
	- Renaissance
	- Neoclassical
	- Romantic
	- Victorian
	- Edwardian
	- Modern
	- Postmodern / contemporary

# Old English (450-1066)
- Famous authors:
	- Caedmon: **Earliest known English poet**
	- Cynewulf
	- St. Venerable Bede
	- Alfred the Great


# Middle English (1066-1500)
\fbox{\parbox{.9\textwidth}{\textbf{Famous authors:}
\begin{itemize}
 \item \textbf{Geoffrey Chaucer} aka \textit{father of English poetry}
 \item William Langland
 \item Thomas Malory
 \item John Gower

\end{itemize}	
}}

# Renaissance (1500-1660)

\scriptsize(\href{https://youtube.com/playlist?list=PL35b_WFpfhcbfCg0xUOjImc-eGDxu3Imf}
 {Playlist covering these (and more!) in detail})\normalsize\vspace{-2mm}

- **4 subperiods:**
	- **Mnemonic:** \btx{লিজা যাবে} car-\btx{এ করে} 
- **Elizabethan** (1558-1603)
	- Replete with lyrics and songs
	- **Golden age of English drama/literature**
	- **Nest of singing birds**
	- **Famous authors:** (Mnemonic: \footnotesize
	\btx{লিলি মার সাথে ফ্রান্স স্পেনে ঘুরছে}\normalsize)
		- **"University Wits"**:
		 (Mnemonic: \btx{মার ঘরে ছেলে পেলে নাচে আর ললি খায়})
		 	- \btx{মার} $\rightarrow$ **Christopher _Marlowe_**
			- \btx{ঘরে} $\rightarrow$ Robert _Greene_
		 	- \btx{ছেলে} $\rightarrow$ Thomas _Kyd_
			- \btx{পেলে} $\rightarrow$ George _Peele_
			- \btx{নাচে} $\rightarrow$ Thomas _Nashe_
			- \btx{ল} $\rightarrow$ Thomas _Lodge_
			- \btx{লি} $\rightarrow$ John _Lyly_
		- Shakespeare
		- Francis Bacon
		- Edmund Spenser
		- John Lyly
- **Jacobean** (1603-1625)
	- Reign of James I $\rightarrow$ Jacobean era
	- **Famous authors:**
		- John Donne
		- Michael Drayton
		- Ben Johnson
		- Elizabeth Cary
- **Caroline** (1625-1649)
	- Reign of Charles I ("Carolus") $\rightarrow$ Caroline era
	- **Famous authors:**
		- John Milton
		- Robert Burton
		- George Herbert
		- _Cavalier poets_:
			- Loyal poets to Charles I
			- Richard Lovelace, Thomas Carew, Sir John Suckling, Edmund Waller,
			 Robert Herrick

- **Commonwealth** (1650-1660)
	- John Milton
	- Thomas Hobbes
	- Thomas Fuller
	- Abraham Cowley
	- Andrew Marvell

# Neoclassical (1660-1785)
- Slogan: **"Art for man's sake"**
- **3 subperiods**
- **Restoration** (1660-1700)
	- William Congreve
	- John Dryden (Congreve and Dryden known for _restoration comedies_)
	- Samuel Butler (_satire_)
	- John Bunyan
	- John Locke
- **Augustan** (1700-1745)
	- Alexander Pope
	- Jonathan Swift
	- Daniel Defoe
	- Henry Fielding
- **Sensibility / Johnson** (1745-1785)
	- Henry Fielding
	- Edmund Burke
	- Edward Gibbon
	- Samuel Johnson
	- Samuel Richardson
	- Hester Lynch Thrale
	- James Boswell
	- Tobias Smollett
	- Laurence Sterne
	- William Cowper
	- Thomas Perry

# Romantic (1800-1832)
- Slogan: **"Art for art's sake"**
- **Famous authors:**
	- Wordsworth
	- Coleridge
	- Keats
	- Blake
	- Shelley (Percy Bysshe and Mary)
	- Byron
	- Jane Austen
	- Charles Lamb

# Victorian (1832-1901)

\fbox{\parbox{.9\textwidth}{\textbf{Poets:}
\begin{itemize}
	\item Alfred Tennyson
	\item Matthew Arnold
	\item Robert and Elizabeth Barrett Browning
\end{itemize}
}}

\fbox{\parbox{.9\textwidth}{\textbf{Essayists:}
\begin{itemize}
	\item Thomas Carlyle
	\item John Ruskin
	\item Walter Pater
\end{itemize}
}}

\fbox{\parbox{.9\textwidth}{\textbf{Novelists:}
\vspace{-5mm}
\begin{columns}[t, totalwidth=.9\textwidth]
\column{0.4\textwidth}
\begin{itemize}
	\item Dickens
	\item Bronte Sisters
	\item Elizabeth Gaskell
	\item George Eliot (penname of Mary Ann Evans)
	\item Anthony Trollope
\end{itemize}
\column{0.5\textwidth}
\begin{itemize}
	\item Thomas Hardy
	\item William Makepeace Thackeray
	\item Samuel Butler (there's also a Restoration era poet by the same name)
\end{itemize}
\end{columns}
}}


```{=latex}
\end{frame}

\newcommand{\outstandingmove}[1]{
\definecolor{springgreen}{RGB}{0, 255, 127}
\definecolor{blueviolet}{RGB}{138, 43, 162}
{
\setbeamercolor{palette primary}{fg=white,bg=blueviolet}
\begin{frame}[standout]
 #1
\end{frame}
}}

\outstandingmove{Important Authors and Literary Works}
\begin{frame}<0>

```
# The Firsts
- **Tragedy:** **Gorboduc** (authors: Thomas Norton and Thomas
 Sackville)
- **Comedy:** **Ralph Roister Doister** (Nicholas Udall) / **Gammer
 Gurton's Needle**
- **Novel:** **Pamela; Virtue Rewarded** (Samuel Richardson)
- **Revenge tragedy:** **The Spanish Tragedy** (Thomas Kyd) 

# Old English Period

\scriptsize(A really good exposition in video format on the Old and Middle
 English periods  \href{https://youtu.be/sYLopdePO2A}{can be found here})
\normalsize\vspace{-3mm}

- Most famous work of the Old English period: **Beowulf**
	- Epic poem (**first English epic**)
	- Author was anonymous
	- **$\boldsymbol\approx \textbf{3200}$ lines**


\blockhead{Caedmon}
- **First known English poet**
- Epithets: _father of English sacred songs_, _Milton of Anglo-Saxon
 period_
- Notable works:
	- **Paraphrase**
	- **Caedmon's Hymn** (poem)
	- Genesis
	- Exodus
	- Judith

\blockhead{Cynewulf}

- Epithet: **author of Christ**
- Notable works:
	- Juliana
	- The Fates of the Apostles
	- Christ
	- Elene

\blockhead{St. Venerable Bede}
- Epithets:
	- Father of English learning
	- First historian in English language
	- Doctor of the Church
- Notable works:
	- An Ecclesiastical History of the English People (book for which he got
	 "Doc of the Church" epithet)

\blockhead{King Alfred the Great}

- **_Founder_ of English prose** (_father_ of English prose = Wycliffe,
 _father_ of _modern_ English prose = Francis Bacon)
- Notable works:
	- **Anglo-Saxon Chronicle** ("first monument in the English prose")


# Middle English Period
\blockhead{Geoffrey Chaucer}

- Epithets:
	- _"The morning star of English literature/renaissance"_
	- **Father of modern poetry**
	- First humourist in English literature
- Notable works:
	- **The Canterbury Tales**
	- **The Nun's Priest's Tale**
	- **Troilus and Criseyde**
	- The Parliament of Fowls/Birds
	- The House of Fame
	- The Legend of Good Women
- Important quotes: _"Time and tide wait for no man"_

\blockhead{John Wycliffe}

- English theologian, philosopher etc
- **First translated the Bible from Latin**
- Epithets:
	- **"Father of English Prose"** (_founder_ of English prose $\rightarrow$
	 Alfred the Great, father of _modern_ English prose $\rightarrow$ F. Bacon)
	- Morning star of reformation
	- Evening star of scholasticism

\blockhead{Sir Thomas Mallory}

- Notable works: **Morte d' Arthur** (first romance in prose)

\blockhead{William Langland}

- Notable works: **Vision of Piers Plowman** (_first great English satire_)
- Important quotes: _"Who will bell the cat?"_

\blockhead{Dante}

- Epithets: 
	- **Father of the Italian language**
	- **Supreme poet of Italy**
- Notable works:
	- **Inferno** (poem)
	- **The Divine Comedy** (epic)

\blockhead{John Gower}

- Notable works:
	- Speculum Homms / Speculum Meditantis
	- Vox Clamantis
	- Confessio Amantis


```{=latex}
\end{frame}
\outstandingmove{The Renaissance}
\begin{frame}<0>
```
# Preparatory Period for the Renaissance
- _First fruit of renaissance_ $\rightarrow$ "Tottel's Miscellany:
 Songs and Sonettes" (Henry Howard and Sir Thomas Wyatt)

\vspace{-3mm}
\blockhead{Sir Thomas More}

- English lawyer and philosopher
- Executed during Henry VIII's reign due to accusations of treason
- Notable works:
	- **Utopia** (1516)
		- Written in Latin
		- Criticism of renaissance English society

\blockhead{Sir David Lindsay}

- Notable works: **The Dream** (poetry)

\blockhead{Nicholas Udall}

- **Father of English Comedy**
- Notable works:
	- **Ralph Roister Doister**: _one of the first comedies_ in English
	 literature, the other one being **Gammer Gurton's Needle**

\blockhead{Henry Howard}

- Earl of Surrey
- **Father of blank verse**

\blockhead{Sir Thomas Wyatt}

- **First Sonneteer in English**


# Elizabethan Period
\blockhead{Edmund Spenser}

- Epithets:
	- **Poet of poets**
	- The child of renaissance / reformation
	- Court poet
	- The divine master / principal poet / prince of poet
- Famous poems:
	- **The Faerie Queene** (epic, allegory)
	- **Amoretti** (sonnets)
	- **The Shepherd's Calendar** (first major work; dedicated to Sir Philip
	 Sidney)
	- **Astrophel** (elegy; on death of Sidney)
	- **Four Hymns**
	- Colin Clouts Came Home Again
	- Mother Hubberd's Tale
	- Complaints
	- Epithalamion


\blockhead{Christopher Marlowe}

- Epithets:
	- **Father of English tragedy**
	- **Father of English drama**
	- "Shakespeare's most important predecessor"
	- "Greatest dramatist before Shakespeare"
- Notable works:

\vspace{3mm}
\begin{columns}[T, totalwidth=\textwidth]
	\hspace{8mm}
	\column{.45\textwidth}
	\fbox{\parbox{.95\textwidth}{
		\scriptsize
		\textbf{Plays:}
		\begin{itemize}
			\tightlist
			\item \textbf{Dr Faustus}
			\item \textbf{Tamburlaine the Great} (\banglatext{তৈমুর লঙ})
			\item \textbf{Edward II}
			\item The Jew of Malta (mnemonic: Malta \rightarrow Marlowe)
			\item You Can Never Tell
		\end{itemize}
		\normalsize
	}}
	\column{.4\textwidth}
	\fbox{\parbox{.9\textwidth}{
		\scriptsize
		\textbf{Poetry:}
			\begin{itemize}
				\tightlist
				\item \textbf{The Passionate Shepherd to His Love}
				\item Pharsalia
				\item Amores
			\end{itemize}
		\normalsize
	}}
\end{columns}


\blockhead{Shakespeare}

- Birth: 1564, Death: 1616
- 37 plays, 154 sonnets
- Discussed in detail in \hyperref[sec:shakes]{this section}.

\blockhead{John Lyly}

- Notable works:
	- Euphues ("bears the embryo of English novel")
	- Midas
	- Campaspe
	- Sapho and Phao

\blockhead{Sir Philip Sidney}

- Notable works:
	- **Arcadia** ("embryo of English novel")
	- **An Apology for Poetry** (literary criticism)
	- **Astrophel and Stella** (sonnet)
	- The Lady of May

\blockhead{Francis Bacon}

- Epithets:
	- **Father of modern English prose**
	- The essayist
- Notable works:
	- \btx{নামের শুরুতে} Of \btx{ওয়ালা সব বই চোখ বুইজা} Francis Bacon \btx{দাগাইবি}
	- Novum Organum (English: New Method)
	- History of Life and Death
	- The New Atlantis


# Jacobean Period

\blockhead{John Donne}

- One of the **metaphysical poets**, others are:
	- Henry Vaughan
	- Andrew Marvell
	- John Cleveland
	- Abraham Cowley
	- George Herbert
	- Richard Crashaw
- Other epithets: **"poet of love", "religious poet"**

\vspace{10mm}

- Notable works:

\hspace{6mm}
\fbox{\parbox{.7\textwidth}{
	\footnotesize
	\vspace{-2mm}
	\begin{columns}[T, totalwidth=.8\textwidth]
	\hspace{-3mm}
	\column{.4\textwidth}
		\begin{itemize}\tightlist
			\item The Good Morrow
			\item The Sun Rising
			\item The Canonization
			\item Twicknam Garden
			\item For Whom the Bell Tolls
		\end{itemize}
	\column{.4\textwidth}
		\begin{itemize}\tightlist
			\item The Anatomy of the world
			\item The Frea
			\item The Ecstasy
			\item The Funeral
		\end{itemize}
	\end{columns}
}}
\vspace{35mm}

\blockhead{John Webster}

- Poet
- Notable works:
	- The Duchess of Malfi
	- The White Devil
	- The Devil's Law Case

\blockhead{George Chapman}

- Notable works: **first English translation of Homer's _Iliad_ and _Odyssey_**

# Commonwealth Period

\blockhead{Andrew Marvell}

- One of the **metaphysical poets**
- Notable works:
	- To His Coy Mistress
	- The Definition of Love
	- The Rehearsal Transposed
	- The Garden

\blockhead{Thomas Hobbes}

- **Political philosopher**
- Notable work: **Leviathan**

\blockhead{Jeremy Taylor}
- English cleric
- Notable works:
	- Holy Living
	- Holy Dying

\blockhead{John Milton}

- Famous **epic poet**
- "A great master of verse in the Puritan period"

\vspace{20mm}

- Notable works:

\footnotesize
\begin{columns}[T, totalwidth=.93\textwidth]
	\hspace{4mm}
	\column{.4\textwidth}
	\fbox{\parbox{.9\textwidth}{
	 \textbf{Epic:}\vspace{-3mm}
		\begin{itemize}
			\tightlist
			\item \textbf{Paradise Lost} (blank-verse epic poem)
			\item Paradise Regained
		\end{itemize}
	}}
	\column{.4\textwidth}
	 \fbox{\parbox{.9\textwidth}{
	 	\textbf{Others:}\vspace{-3mm}
		\begin{itemize}
			\tightlist
			\item Comus
			\item Lycidas (a pastoral elegy, written on the death of Edward
			 King, friend of Milton)
			\item Of Education
			\item Areopagitica (pamphlet)
		\end{itemize}
	}}
\end{columns}
\normalsize

```{=latex}
\end{frame}
\outstandingmove{The Neoclassical}
\begin{frame}<0>
```

# Restoration Period

\blockhead{William Congreve}

- His comedy is known as **"comedy of manners"** (Ben Johnson $\rightarrow$
 _"comedy of humours"_)
- Notable works:
	- The Way of the World
	- Love for Love
	- The Double Dealer
	- The Old Bachelor

\vspace{10mm}
\blockhead{John Dryden}

- **Father of English criticism**
- Notable works:

\hspace{5mm}
\fbox{\parbox{.8\textwidth}{
	\vspace{-2mm}
	\begin{columns}[T, totalwidth=.8\textwidth]
	\hspace{-3mm}
	\column{.4\textwidth} 
	\footnotesize
	\begin{itemize}\tightlist
		\item All for Love
		\item The Indian Emperor
		\item Aurang-zebe
		\item The Mistaken Husband 
		\item Absalom and Achitophel
	\end{itemize}
	\column{.4\textwidth}
	\footnotesize
	\begin{itemize}\tightlist
		\item Macflecknoe
		\item The Essay of Dramatic Poesy
		\item The Conquest of Granada
		\item The Medal of John Bays
	\end{itemize}
	\end{columns}
}}

\vspace{15mm}
\blockhead{Samuel Butler}

- English novelist
- Notable works: Hudibras (famous satire in verse)

\blockhead{John Bunyan}

- English writer and Puritan preacher
- Notable works: **The Pilgrim's Progress** (an allegory)

\blockhead{John Locke}

- English philosopher whose works lie at the _foundation of modern
 philosophical empiricism and political liberalism_
- Notable works:
	- An Essay Concerning Human Understanding
	- Two Treatises of Government

# Augustan Period

\blockhead{Alexander Pope}

- **Mock heroic poet**
- Notable works:
	- An Essay on Criticism
	- The Dunciad
	- The Imitation of Horace
	- An Essay on Man
	- Letter to Gay
	- The Rape of the Lock (epic)

\vspace{15mm}
\blockhead{Jonathan Swift}

- **Greatest satirist of 18th century**
- Notable works:
	- Gulliver's travels
	- A Tale of A Tub
	- The Battle of the Books
	- A Modest Proposal
	- A Journey to Stella

\vspace{15mm}
\blockhead{Daniel Defoe}

- Notable works:
	- Novels:
		- Captain Singleton
		- Robinson Crusoe:
			- Key characters: Crusoe, Friday
		- Moll Flanders
		- Colonel Jack
		- Roxana: The Fortunate Mistress
	- Poem: The True-Born Englishman

\blockhead{Henry Fielding}

- **Father of English novel**
- Notable works:

\vspace{-3mm}
\begin{columns}[T, totalwidth=.93\textwidth]
\footnotesize
\hspace{6mm}\column{.35\textwidth}
\fbox{\parbox{.9\textwidth}{
	\textbf{Novels:}\vspace{-3mm}
	\begin{itemize}\tightlist
		\item \textbf{Tom Jones}
		\item Amelia
		\item Joseph Andrews
		\item Jonathan Wilde
		\item Top Secret
	\end{itemize}	
}}
\column{.45\textwidth}
\fbox{\parbox{.9\textwidth}{
	\textbf{Play:}\vspace{-3mm}
	\begin{itemize}\tightlist
	\item Rape Upon Rape
	\item The Temple Beau
	\item The Tragedy of Tragedies
	\item The Modern Husband
	\end{itemize}
}}
\end{columns}

# Sensibility/Johnson Period

\blockhead{Oliver Goldsmith}

- Irish novelist, playwright, poet
- Notable works:
	- The Citizen of the World
	- The Vicar of the Wakefield
	- The Traveller
	- The Deserted Village
	- The Good-Natured Man
	- She Stoops to Conquer

\vspace{15mm}
\blockhead{Thomas Gray}
- Notable works: Elegy Written in a Country Churchyard


```{=latex}
\end{frame}
\outstandingmove{William Shakespeare}
\begin{frame}<0>
```
# William Shakespeare

\label{sec:shakes}

\scriptsize(\href{https://youtu.be/PnOMXg4RIQk}{Detailed video on Shakes})
\normalsize

\blockhead{Early Life}

- Birth: Apr 23, 1564; at Stratford on Avon
- Death: Apr 23, 1616 (aged 52)
- Buried: Apr 25, 1616
- Marriage: 1582, to Anne Hathaway (8y elder than Shakes)

\vspace{15mm}
\blockhead{Literary Career}

\vspace{2mm}
\begin{columns}[T, totalwidth=.9\textwidth]
\scriptsize
\column{.3\textwidth}
\fbox{\parbox{\textwidth}{
	\textbf{Statistics}
	\vspace{-2mm}
	\begin{columns}[T, totalwidth=\textwidth]
		\column{.65\textwidth}
		\begin{itemize}[leftmargin=1mm]\tightlist
			\item[] Plays
			\item[] Sonnets
			\item[] Narrative poems
			\item[] Acts in his plays
		\end{itemize}
		\column{.35\textwidth}
		\begin{itemize}[leftmargin=2mm]\tightlist
			\item[] 37
			\item[] 154
			\item[] 3
			\item[] 5
		\end{itemize}
	\end{columns}
}}

\column{.5\textwidth}
\fbox{\parbox{\textwidth}{
	\textbf{The Extremes}
	\vspace{-2mm}
	\begin{columns}[T, totalwidth=\textwidth]
		\column{.5\textwidth}
		\begin{itemize}[leftmargin=1mm]\tightlist
			\item[] 1st staged play
			\item[] Last play (swan song)
			\item[] Shortest play
			\item[] Longest play
		\end{itemize}
		\column{.5\textwidth}
		\begin{itemize}[leftmargin=1mm]\tightlist
			\item[] Henry VI (Pt. 2)
			\item[] The Tempest
			\item[] The Comedy of Errors
			\item[] Hamlet
		\end{itemize}
	\end{columns}
}}

\end{columns}\vspace{1mm}

- Epithets:
	- **Bard of Avon**
	- **King without a Crown**
- Literary style: iambic pentameter (5 stressed syllables and 5 unstressed
 syllables within each line)

\rowcolors{2}{gray!20}{gray!40}
\begin{table}[h!]
\scriptsize
\centering
\begin{tabular}{m{.22\textwidth} m{.22\textwidth} m{.22\textwidth} m{.22\textwidth}}
\cellcolor{violet!60}\color{white}Tragedy &
\cellcolor{violet!60}\color{white}Comedy &
\cellcolor{violet!60}\color{white}Historical &
\cellcolor{violet!60}\color{white}Poem \\
\textbf{Hamlet} & \textbf{All's Well That Ends Well} & Henry IV Pt. 1 & \textbf{Lover's complaint} \\
\textbf{Romeo and Juliet} & \textbf{As You Like It} & Henry IV Pt. 2 & \textbf{Passionate Pilgrim} \\
\textbf{Julius Caesar} & \textbf{Comedy of Errors} & Henry V & \textbf{Phoenix and the Turtle} \\
\textbf{Othello} & Love's Labour's Lost & Henry VI Pt. 1 & \textbf{Rape of Lucrece} \\
\textbf{King Lear} & \textbf{Measure for Measure} & Henry VI Pt. 2 & \textbf{Venus and Adonis} \\
\textbf{Macbeth} & \textbf{Merchant of Venice} & Henry VI Pt. 3 &  \\
Titus Andronicus & Merry Wives of Windsor & Henry VIII &  \\
\textbf{Antony and Cleopatra} & \textbf{Midsummer Night's Dream} & King John &  \\
Troilus and Cressida & Much Ado About Nothing & Richard II &  \\
\end{tabular}

\vspace{15mm}
\begin{tabular}{m{.22\textwidth} m{.22\textwidth} m{.22\textwidth} m{.22\textwidth}}
\cellcolor{violet!60}\color{white}Tragedy &
\cellcolor{violet!60}\color{white}Comedy &
\cellcolor{violet!60}\color{white}Historical &
\cellcolor{violet!60}\color{white}Poem \\

\textbf{Timon of Athens} & \textbf{Taming of the Shrew} & Richard III &  \\
Coriolanus & \textbf{The Tempest} &  &  \\
Cymbeline & \textbf{All's Well That Ends Well} &  &  \\
 & Two Gentlemen of Verona &  &  \\
 & Winter's Tale &  &  \\
 & Pericles, Prince of Tyre &  &  \\
 & Twelfth Night &  &  \\
\end{tabular}
\vspace{3mm}\caption{Important works of Shakespeare}
\label{table:shakes.txt}
\end{table}
