---
title: International Organisations
subtitle: The Bare Minimum for BCS
author: Susmit Islam
institute: Sir Salimullah Medical College
documentclass: beamer
output:
 beamer_presentation:
  keep_tex: yes
theme: metropolis
classoption: progressbar=frametitle
fontsize: 10pt
header-includes:
  - \setbeamersize{text margin left=10mm,text margin right=10mm}
  - \setbeamertemplate{frametitle continuation}{}
  - \usepackage{bangla}
  - \usepackage{enumitem}
  - \setlistdepth{20}
  - \renewlist{itemize}{itemize}{20}
  - \renewlist{enumerate}{enumerate}{20}
  - \setlist[itemize]{label=$*$}
  - \setlist[itemize,1]{label=\tiny$\blacksquare$}
  - \setlist[itemize,2]{label=$\bullet$}
  - \setlist[itemize,3]{label=$\boldsymbol\circ$}
  - \setlist[itemize,4]{label=$*$}
  - \linespread{1.3}
---
# Preface {-}
What follows are my notes on International Organisations.
 Many of these things change quite frequently
 and so these notes may be out of date when you read them. Proceed with caution.
 There's probably plenty of mistakes, all my own.
 Inform me whenever you find one.\newline
 
**Use at your own peril.**

\hfill Susmit Islam

\hfill\today
 
# Commonwealth of Nations
- **Intro:** political organisation, largely composed of former British
 colonies
- **Establishment:**
	- **Balfour declaration:** $\rightarrow$ "British Commonwealth of Nations" (1926)
	- Statute of Westminster (1931) made the dominions their own sovereign
	 states
	- **London declaration** $\rightarrow$ "Commonwealth of Nations" (1949)
- **Members:** 56
	- **Latest members:** Togo, Gabon (2022)
	- The last 4 members are the only ones that have never been British
	 colonies
		- Mozambique (1st non-colony member; 2009)
		- Rwanda (2009)
		- Togo (2022)
		- Gabon (2022)
- **HQ:** Marlborough house, London.
- **Head:** Queen Elizabeth II.

# NAM (Non-Aligned Movement)
- **Intro:** Formed during the Cold War by countries supporting neither the
 Soviet nor the US.
- **Establishment:** 1961; Belgrade, Yugoslavia.
- **Members:** 120 members, 20 observers.
- **HQ:** None

# OIC (Organisation of Islamic Co-operation)
- **Intro:** Made in the wake of the Arab-Israel war
- **Establishment:**
	- Sep 25, 1969, as Organisation of Islamic Conference
	- Changed to current name in 2011
- **Members:** 57
- **HQ:** Jeddah
- **1st sec. gen.:** Tunku Abdul Rahman (Malaysia)
- **Current sec. gen.:** Hissein Brahim Taha (Chad)

# EU (European Union)
- **Intro:**
	- World's largest economic union
	- Political and economic union, with an internal single market
	- After the end of the Cold War and the unification of Germany,
	 to "further advance European integration"
- **Establishment:**
	- **Treaty of Rome:** (1957)
		- Established **European Economic Community (EEC)**
		- Signed by 6 countries: Belgium, France, Netherlands, W. Germany,
		 Italy, Luxembourg
		- Signed: Mar 25, 1957
		- Effective: Jan 1, 1958
		- After formation of EU, renamed to European Community (EC)
		- Was one of the "3 pillars" of EU till 2009, when the 3-pillar system
		 was abolished and the functions of the pillars were absorbed into EU
	- **Treaty of Maastricht:** (1992; Maastricht, Netherlands)
		- Signed by 12 countries marking the beginning of EU
		- Signed: Feb 7, 1992.
		- Effective: Nov 1, 1993.
	- **Treaty of Lisbon:** (2007)
		- Initially called "Reform Treaty"
		- Amendment of the Maastricht treaty
		- Signed: Dec 13, 2007
		- Effective: Dec 1, 2009
		- Abolished the 3-pillar system and marked the emergence of the EU
		 as a legal person
		 - In 2012, the EU received the Nobel Peace Prize
- **Members:** 27
- **HQ:** Brussels, Belgium.
- **Structure:**
	- 7 institutions, 1st 4 are the main decision-making institutions
		- \fbox{European Parliament}
			- Location: Strasbourg (France), Brussels, Luxembourg
			- Members: 705 MEPs (members of European parliament)
		- \fbox{European Council}
			- Location: Brussels
			- Members: Heads of state of EU member countries
			- President: Charles Michel
		- \fbox{Council of the EU}
			- Location: Brussels
			- Members: Ministers of EU member countries
		- \fbox{European Commission}
		- \fbox{Court of Justice of the EU}
			- Location: Luxembourg
		- \fbox{European Central Bank}
			- Location: Frankfurt, Germany
			- Members: ECB President and Vice-President
			 and governors of national central banks from all EU countries
- **Euro:**
	- "Members":
		- 19 member states, together called **eurozone / euro area**, have adopted
		 the euro as their primary currency.
		- Croatia will become the 20th member on Jan 1, 2023
		- Other EU members can join the eurozone when they fulfill the criteria
		 for joining
	- Launch:
		- Jan 1, 1999
		- 11 member states had met the criteria back then, and hence those
		 11 were the firsts to adopt the euro
		- Physical notes and coins were launched on Jan 1, 2002.

# AU (African Union)
- **Establishment:**
	- **OAU (Organisation of African Unity)** $\rightarrow$ May 25, 1963
	- **Sirte declaration** $\rightarrow$ Sep 9, 1999 (9/9/99); signed by
	 heads of OAU states
	- **AU** officially launched in Jul 9, 2002.
- **Members:** 55
	- **Latest member:** Morocco (2017)
	- All African nations are members
	- Morocco was a founding member of OAU, but quit in 1984 due to the
	 acceptance of Sahrawi Arab Democratic Republic as a member state,
	 most of the territory of which is ruled by Morocco. Nonetheless,
	 it is a partially recognised sovereign state, with 41 UN nations
	 recognising it.
- **HQ:** Addis Ababa.
- **Chairperson:** Macky Sall (President of Senegal)

# Arab League
- **Establishment:**
	- **Alexandria protocol** (1945) $\rightarrow$ **Arab league** (Mar 22, 1945)
- **Members:**
	- Member states: 22
	- Observer states: 7
		- Armenia
		- Brazil
		- Chad
		- Eritrea
		- Greece
		- India
		- Venezuela
	- Latest member: Comoros (1993)
	- Suspended member: Syria (since 2011)
- **Probably unrelated fact:** Egypt and Syria formed the **United Arab
 Republic** in 1958 (capital: Cairo). In 1961, Syria quit the union, and
 Egypt continued to be officially known as the UAR until 1971. 

# OAS (Organization of American States)
- **Establishment:** Apr 30, 1948.
- **Members:** 35
	- All independent nations of the Americas are members
	- Founding members: 21
	- Latest member: Guayana (1991)

# GCC (Gulf Cooperation Council)
- **Intro:** Union of countries bordering the Persian gulf
- **Establishment:** May 25, 1981
- **Members:** Bahrain, Kuwait, Oman, Qatar, KSA, UAE
- **HQ:** Riyadh

# G-7 (Group of 7)
- **Intro:** Avengers, basically. Big-shot governments join forces to
 discuss and coordinate solutions to major global issues in trade,
 security, economics, and climate change.
- **Members:** 7
	- USA
	- Canada
	- UK
	- Germany
	- France
	- Italy
	- Japan
- **Establishment:**
	- Mar 25, 1973 $\rightarrow$ G5
	- Nov 15, 1975 $\rightarrow$ G6 (Italy added)
	- 1976 $\rightarrow$ G7 (Canada added)
	- 1997 $\rightarrow$ G8 (Russia added)
	- 2014 $\rightarrow$ G7 (Russia suspended over annexation of Crimea)
- **HQ:** None

# G-20
- **Intro:** "the primary venue for international economic and financial
 cooperation"
- **Establishment:** Sep 26, 1999.
- **Members:** 20
	- 19 countries + the EU
		- G-7 countries (7)
		- BRICS countries (5): Brazil, Russia, India, China, South Africa
		- Others (7): ARG, AUS, KSA, KOR (Republic of Korea aka South Korea),
		 MEX, IDN (Indonesia), TUR (Turkey)
- **HQ:** None

# D-8 (Developing 8)
- **Establishment:**
	- **Istanbul declaration** (Jun 15, 1997) $\rightarrow$ D-8
- **Members:** 8 states. Mnemonic: \banglatext{বাপ মা নাই তুমিই সব}
	- Bangladesh
	- Pakistan
	- Malaysia
	- Nigeria
	- Turkey
	- Egypt (\banglatext{মিশর})
	- Iran
- **HQ:** Istanbul

# OPEC (Organisation of Petroleum Exporting Countries)
- **Intro:** Control oil prices worldwide. Responsible for 44% of the total
 oil production worldwide.
- **Establishment:**
	- Through Baghdad conference (Sep 10-14, 1960), attended by the founding 5
		- Iraq
		- Iran
		- KSA
		- Kuwait
		- Venezuela
- **Members:** 13
	- Founding 5
	- Other current members:
		- Algeria
		- Angola
		- Congo
		- Equatorial Guinea
		- Gabon
		- Libya
		- Nigeria
		- UAE
	- Former members: Ecuador, Indonesia, Qatar
- **HQ:** Vienna

# APEC (Asia-Pacific Economic Co-operation)
- **Intro:** Promotes free trade throughout countries in the pacific rim
- **Establishment:** 1989
- **Members:** 21
- **HQ:** Singapore

# CIRDAP
- Centre on Integrated Rural Development for Asia and the Pacific
- **Intro:** _Bangladesh based_ organisation for rural development and
 poverty alleviation
- **Establishment:**
	- Date: Jul 6, 1979
	- Initiative by countries in the Asia-Pacific region and FAO of the UN
- **Members:**
	- Founding 6
	- Currently 15
- **HQ:** Chameli house, Dhaka (in front of the Supreme Court)
- **Director General:** Dr Cherdsak Virapat (Thailand)

# ASEAN
- Association of South East Asian Nations
- **Establishment:**
	- Bangkok declaration / ASEAN declaration:
		- Aug 8, 1967
		- Signed by founding 5: Indonesia, Malaysia, Philippines, Singapore,
		 Thailand
- **Members:** 10 countries. Mnemonic: MTV \banglatext{তে} FILM \banglatext{দেখলে}
 BCS \banglatext{হবেনা}
	- Malaysia
	- Thailand
	- Vietnam
	- Philippines
	- Indonesia
	- Laos
	- Myanmar
	- Brunei
	- Cambodia
	- Singapore
- **HQ:** Jakarta
- **Summit:** Every 3 yrs.		

# SAARC
- South Asian Association for Regional Cooperation
- **Establishment:**
	- Dec 8, 1985: signing of SAARC declaration
- **Members:** 8 members, 9 observers.
	- Members mnemonic: BNP IS MBA.
		- Bangladesh
		- Nepal
		- Pakistan
		- India
		- Sri Lanka
		- Maldives
		- Bhutan
		- Afghanistan
	- Latest member: AFG (2007)
- **HQ:** Kathmandu
- **Summit:**
	- No specific interval, although the official charter requires a summit
	 every 18 mo
	- First summit: Dec 7-8, 1985
	- Latest (20th): 2022 (to be held)
- **Sec. Gen.:**
	- 1st: Abul Ahsan (BD)
	- Current: Esala Ruwan Weerakoon (SL)
